name: bottender_app
description: BotTender mobile app for BotTender device.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  freezed: ^2.4.1
  lan_scanner: ^4.0.0+1
  network_tools: ^5.0.2
  async_redux: ^21.4.0
  freezed_annotation: ^2.4.1
  provider_for_redux: ^7.0.1
  oktoast: ^3.3.1
  http: ^1.2.1
  json_serializable: ^6.7.1
  device_info_plus: ^10.1.0
  loader_overlay: ^4.0.0
  flutter_svg: ^2.0.7
  network_info_plus: ^5.0.2
  permission_handler: ^11.3.0
  flutter_bluetooth_serial: ^0.4.0
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  connectivity_plus: ^6.0.1
  android_flutter_wifi: ^0.1.2
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.7.0
  cloud_firestore: ^4.15.8
  cloud_functions: ^4.6.8
  simple_barcode_scanner: ^0.1.1
  image_cropper: ^6.0.0
  image_picker: ^1.0.7
  firebase_storage: ^11.7.1
  flutter_image_compress: ^2.2.0

dev_dependencies:
  build_runner: ^2.0.0
  very_good_analysis: ^5.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/device_icon.jpeg
    - assets/images/ingredient_icon.png
    - assets/svg/empty_page.svg
    - assets/svg/config_device_page.svg

  uses-material-design: true
